fabric/contrib/project.py

The description says "ends with a trailing slash" but the example does **not** end with a trailing slash.

missing a trailing slash in E.g. of docstring

---

tests/Python26SocketServer.py

The build is failing because of a non-ASCII character. The file's encoding could be updated, or the character could be swapped, which is included in this commit.

Swapped non-ASCII character for (c) to fix broken build

---

fabric/operations.py
tests/test_context_managers.py

This redirects the output of the `cd` command to `/dev/null` so that in cases where `CDPATH` is set, the output from `cd` won't be captured. Will not add the redirect on Windows. Fixes #980.

Redirect cd output to /dev/null in case of CDPATH

---

fabric/job_queue.py

Fixes an example for the job queue constructor (which now requires a second positional argument, intended to be a Queue() object)
Also addresses <https://github.com/fabric/fabric/issues/1305#issuecomment-92333680> . We'll now only set exit status if it's a process and do nothing if it's a thread.

Fix example of Job Queue

---

dev-requirements.txt
sites/docs/index.rst
sites/docs/running_tests.rst

Here's a first blush at docs around running tests. The `alabaster` bump was necessary because Sphinx locally refused to build (`pkg_resources.DistributionNotFound: alabaster>=0.7,<0.8`), which is a separate commit so it can be cherry-picked if necessary.
Fixes #1309

Docs on "Running Tests"

---

README.rst

For folks who are new to Fabric (or coming back to after a long time), it can take sometime to figure out about the default file ``fabfile.py``, so just mentioning that explicitly.

Make it explicit that the sample needs to be saved as fabfile.py

---

fabric/io.py
fabric/network.py
tests/test_network.py
tests/test_tasks.py

Nested executions using non-default ports did not work as env.port was prioritized over hostname and ssh config derived port numbers.
See test_tasks.py:TestExecute.test_nested_execution_with_explicit_ports

fix nested executions using non-standard ports

---

fabric/contrib/files.py

Jinja2 by default will trim a single trailing newline.
http://jinja.pocoo.org/docs/dev/templates/#whitespace-control
Most time we will need this trailing newline IMHO :)

allow trailing newline in Jinja2

---

CHANGELOG.rst

I couldn't find the changelog until I did quite a bit of searching, because it's hidden in a subdirectory.
I propose the following patch -- it simply adds a CHANGELOG.rst file on the top level (where one would expect it to me) that identifies the actual changelog, and gives a link to the HTML version on fabfile.org

Expose the Changelog

---

fabric/network.py
fabric/state.py

Support 3 additional parameters when connecting to hosts: gss-auth,
gss-deleg, gss-kex. These correspond to the equivalent in paramiko. It
does all the hard work.

Initial support for using Kerberos.

---

fabric/operations.py

This PR is to add a kwarg to reboot to allow ```run``` instead of just ```sudo``` within the reboot function.
No test written as no test currently exists for reboot.
Output from pylint is:
```
pylint2 -E operations.py 
No config file found, using default configuration
************* Module fabric.operations
E:827,54: Instance of 'list' has no 'endswith' member (but some types could not be inferred) (maybe-no-member)
E:828,53: Instance of 'list' has no 'endswith' member (but some types could not be inferred) (maybe-no-member)
```
Which isn't related to my change (though after looking at the code I can see why pylint is confused).

Added use_sudo as a kwarg to the reboot function.

---

fabric/contrib/files.py
sites/www/changelog.rst
tests/test_contrib.py

Adds keyword argument `case_sensitive=True` to contrib.files.contains().

Feature #1203: Case-insensitive matching for contrib.files.contains()

---

fabric/operations.py
sites/www/changelog.rst

Reverses the order in which `shell_env` and `prefix` are applied to a command.

Fixes #1135. Command prefix is applied before shell_env.

---

fabric/decorators.py

This is in prep for bumping the paramiko dependency, where Cryptography is used instead of PyCrypto.

Handle Fabric-level assumptions about PyCrypto's use

---

fabric/network.py
sites/www/changelog.rst

fixes #1514 
(restores python2.5 compatibility)
I tested with python2.7 by just running a task which runs commands on a remote server - I'm just assuming, without looking too closely, that this connect() function was called. Also ran "nosetests" - but the change is about as small as they get anyway :)

avoid use of str.format() in network.py

---

fabric/contrib/files.py

Some (uncommon) systems can end up with shell escapes in the output
of run("uname"), so don't use shell (or pty), they're not needed anyway.
fixes #1526 / #1527
Figured this was another very easy little "fix". I'm happy to re-target to whatever branch is desired.
There is an integration test for `contrib.sed()` (already), which should be a reasonable sanity-test that I didn't break it...

contrib.sed(): avoid shell for uname

---

tests/test_contrib.py

escaping of the text for contains() changed in #1559

tests: update contrib.files.contains() case_sensitive test fixtures

---

fabric/sftp.py
sites/www/changelog.rst
tests/test_operations.py

This was using a hash of the host and remote file path,
and could result in an unnecessary failure if there were
multiple get() and/or put() of the same file path on the same host
simultaneously.
fixes #1555

put() and get(): use random temp file when use_sudo=True

---

sites/www/development.rst

Note: this is an ad-hoc PR, done entirely via the GitHub interface (i.e., no local checkout).

Fix link to contribution-guide.org

---

sites/docs/concepts/configuration.rst

`load_openssh_configs` does not appear anywhere in the source. It appears that it should be `load_ssh_configs`.

Fix typo in configuration docs
